version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub composite Actions (/.github/actions)
  # Waiting for supporting wildcards see https://github.com/dependabot/dependabot-core/issues/5137
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/azure-login"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/do-login"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/docker-build"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      graphql-kotlin:
        patterns:
          - "com.expediagroup:graphql-kotlin-*"
      maven-core:
        patterns:
          - "org.apache.maven:maven-*"
      jackson:
        patterns:
          - "com.fasterxml.jackson.*:jackson-*"
      jetty:
        patterns:
          - "org.eclipse.jetty:*"
      jwt:
        patterns:
          - "io.jsonwebtoken:jjwt-*"
      logback:
        patterns:
          - "ch.qos.logback:*"
      jakarta-apis:
        patterns:
          - "jakarta.*:*"
      rest-assured:
        patterns:
          - "io.rest-assured:*"
      quarkus-logging:
        patterns:
          - "io.quarkiverse.logging.logback:*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: "/deploy"
    schedule:
      interval: "daily"
