version: '3.6'
services:
  mongodb:
    image: mongo:4.2
    ports:
      - "127.0.0.1:27017:27017"
  frontend:
    depends_on:
      - mongodb
    image: "adoptium-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      MONGODB_HOST: mongodb
  updater:
    depends_on:
      - mongodb
    image: "adoptium-api"
    command: "java -jar /deployments/adoptium-api-v3-updater-runner.jar"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_HOST: mongodb
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      GITHUB_APP_ID: "${GITHUB_APP_ID}"
      GITHUB_APP_PRIVATE_KEY: "${GITHUB_APP_PRIVATE_KEY}"
      GITHUB_APP_INSTALLATION_ID: "${GITHUB_APP_INSTALLATION_ID}"
