####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the docker image run:
#
# mvn package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/adoptium-api-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/adoptium-api-jvm
#
###
FROM eclipse-temurin:25-jammy
ENV JAVA_TOOL_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY target/quarkus-app/. /deployments/
ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]
