name: DigitalOcean Login
description: Logs in to DigitalOcean
inputs:
    DIGITALOCEAN_ACCESS_TOKEN:
      description: 'DigitalOcean access token'
      required: true
runs:
  using: composite
  steps:
  - name: Login to DigitalOcean
    uses: digitalocean/action-doctl@e5cb5b0cde9789f79c5115c2c4d902f38a708804 # v2.5.0
    with:
      token: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}

  - name: Set the target Azure Kubernetes Service (AKS) cluster.
    shell: bash
    run: doctl kubernetes cluster kubeconfig save k8s-1-27-4-do-0-blr1-1693486270021
