name: Docker Build
description: Build and push Docker images to Azure Container Registry
inputs:
    DOCKER_REPO:
      description: 'Docker repository'
      required: true
    BUILD_ARGS:
      description: 'Build arguments'
      required: false
runs:
  using: composite
  steps:
  - name: Build container image and push to Azure
    uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
    with:
      file: ./deploy/Dockerfile
      tags: ${{ inputs.DOCKER_REPO }}:latest
      build-args: ${{ inputs.BUILD_ARGS }}
      push: true
