name: CI

on:
  pull_request:
    branches: [ main, production ]
  push:
    branches: [ main, production ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ecosystem: [adoptium, adoptopenjdk]

    steps:
    - name: Setup mvnw arguments
      run: |
        case ${{ matrix.ecosystem }} in
          adoptium) echo "ARGS=-Padoptium,-adoptopenjdk" >> $GITHUB_ENV ;;
          adoptopenjdk) echo "ARGS=-Padoptopenjdk,-adoptium" >> $GITHUB_ENV ;;
        esac

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build app
      run: ./mvnw --batch-mode clean install ${{ env.ARGS }}
