name: CI

on:
  pull_request:
    branches: [ main, production ]
  push:
    branches: [ main, production ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ecosystem: [adoptium, adoptopenjdk]

    steps:
    - name: Setup mvnw arguments
      run: |
        case ${{ matrix.ecosystem }} in
          adoptium) echo "ARGS=-Padoptium,-adoptopenjdk" >> $GITHUB_ENV ;;
          adoptopenjdk) echo "ARGS=-Padoptopenjdk,-adoptium" >> $GITHUB_ENV ;;
        esac

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'temurin'
        #cache: 'maven'
        verify-signature: true

    - name: Build app
      run: ./mvnw --batch-mode clean install ${{ env.ARGS }}
